- name: Hello World Sample
  hosts: localhost
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
    - name: Check the Cstate of all NIM clients
      ibm.power_aix.nim:
        action: check
      no_log: "{{ no_log_val }}"



